AWS_ACCESS_KEY_ID = "AKIA2FXAEBTOK6CZFDPM"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"
BUCKET_NAME = "heathrecords"
GEMINI_API_KEY = "AIzaSyAwlJ-6BfIS3HeMPsjYU9Pc0A89lgykjuw"
